# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #00365f;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.Cam = QtWidgets.QLabel(self.centralwidget)
        self.Cam.setGeometry(QtCore.QRect(380, 20, 601, 491))
        self.Cam.setStyleSheet("QLabel{\n"
"    border-radius: 20px;\n"
"    border: 5px solid #ffbe00;\n"
"}")
        self.Cam.setText("")
        self.Cam.setObjectName("Cam")
        self.SpdFram = QtWidgets.QFrame(self.centralwidget)
        self.SpdFram.setGeometry(QtCore.QRect(50, 310, 271, 81))
        self.SpdFram.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    border: 5px solid #ffbe00;\n"
"}")
        self.SpdFram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SpdFram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SpdFram.setObjectName("SpdFram")
        self.HiSpd1 = QtWidgets.QFrame(self.SpdFram)
        self.HiSpd1.setGeometry(QtCore.QRect(180, 10, 31, 61))
        self.HiSpd1.setStyleSheet("QFrame{\n"
"    background-color: #6b0000;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: red;\n"
"}")
        self.HiSpd1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HiSpd1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HiSpd1.setObjectName("HiSpd1")
        self.LowSpd2 = QtWidgets.QFrame(self.SpdFram)
        self.LowSpd2.setGeometry(QtCore.QRect(60, 10, 31, 61))
        self.LowSpd2.setStyleSheet("QFrame{\n"
"    background-color: #1b611a;\n"
"    border: none;\n"
"}\n"
"QFrame:hover{\n"
"    background-color: #04ff00;\n"
"}")
        self.LowSpd2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LowSpd2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LowSpd2.setObjectName("LowSpd2")
        self.MidSpd2 = QtWidgets.QFrame(self.SpdFram)
        self.MidSpd2.setGeometry(QtCore.QRect(140, 10, 31, 61))
        self.MidSpd2.setStyleSheet("QFrame{\n"
"    background-color: #858517;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #ffff00;\n"
"}")
        self.MidSpd2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MidSpd2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MidSpd2.setObjectName("MidSpd2")
        self.HiSpd2 = QtWidgets.QFrame(self.SpdFram)
        self.HiSpd2.setGeometry(QtCore.QRect(220, 10, 31, 61))
        self.HiSpd2.setStyleSheet("QFrame{\n"
"    background-color: #6b0000;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: red;\n"
"}")
        self.HiSpd2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HiSpd2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HiSpd2.setObjectName("HiSpd2")
        self.LowSpd1 = QtWidgets.QFrame(self.SpdFram)
        self.LowSpd1.setGeometry(QtCore.QRect(20, 10, 31, 61))
        self.LowSpd1.setStyleSheet("QFrame{\n"
"    background-color: #1b611a;\n"
"    border: none;\n"
"}\n"
"QFrame:hover{\n"
"    background-color: #04ff00;\n"
"}")
        self.LowSpd1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LowSpd1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LowSpd1.setObjectName("LowSpd1")
        self.MidSpd1 = QtWidgets.QFrame(self.SpdFram)
        self.MidSpd1.setGeometry(QtCore.QRect(100, 10, 31, 61))
        self.MidSpd1.setStyleSheet("QFrame{\n"
"    background-color: #858517;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #ffff00;\n"
"}")
        self.MidSpd1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MidSpd1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MidSpd1.setObjectName("MidSpd1")
        self.DirFrm = QtWidgets.QFrame(self.centralwidget)
        self.DirFrm.setGeometry(QtCore.QRect(60, 30, 261, 261))
        self.DirFrm.setStyleSheet("QFrame{\n"
"    border-radius: 130px;\n"
"    border: 5px solid #ffbe00;\n"
"}")
        self.DirFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DirFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DirFrm.setObjectName("DirFrm")
        self.UpperLeft = QtWidgets.QFrame(self.DirFrm)
        self.UpperLeft.setGeometry(QtCore.QRect(50, 60, 60, 60))
        self.UpperLeft.setStyleSheet("QFrame{\n"
"    border: none;\n"
"    background-color: qconicalgradient(cx:0.7, cy:0.1, angle:225, stop:0.499 rgba(0, 0, 0, 0), stop:0.5 rgba(0, 88, 174, 255));\n"
"}")
        self.UpperLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UpperLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UpperLeft.setObjectName("UpperLeft")
        self.Center = QtWidgets.QFrame(self.DirFrm)
        self.Center.setGeometry(QtCore.QRect(100, 100, 60, 60))
        self.Center.setStyleSheet("QFrame{\n"
"    background-color: #0058ae;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #09edeb;\n"
"}")
        self.Center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Center.setObjectName("Center")
        self.UpperRight = QtWidgets.QFrame(self.DirFrm)
        self.UpperRight.setGeometry(QtCore.QRect(150, 60, 60, 60))
        self.UpperRight.setStyleSheet("QFrame{\n"
"background-color: qconicalgradient(cx:0.3, cy:0.1, angle:135, stop:0.499 rgba(0, 0, 0, 0), stop:0.5 rgba(0, 88, 174, 255));\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: qconicalgradient(cx:0.3, cy:0.1, angle:135, stop:0.499 rgba(0, 0, 0, 0), stop:0.5 rgba( 9, 237, 235, 255));\n"
"}")
        self.UpperRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UpperRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UpperRight.setObjectName("UpperRight")
        self.Right = QtWidgets.QFrame(self.DirFrm)
        self.Right.setGeometry(QtCore.QRect(180, 100, 60, 60))
        self.Right.setStyleSheet("QFrame{\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:225, stop:0.75 rgba(0, 88, 174, 255), stop:0.749 rgba(0, 0, 0, 0));\n"
"    border: none;\n"
"}")
        self.Right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Right.setObjectName("Right")
        self.LowerLeft = QtWidgets.QFrame(self.DirFrm)
        self.LowerLeft.setGeometry(QtCore.QRect(50, 140, 60, 60))
        self.LowerLeft.setStyleSheet("QFrame{\n"
"    border: none;\n"
"    background-color: qconicalgradient(cx:0.7, cy:0.9, angle:315, stop:0.499 rgba(0, 0, 0, 0), stop:0.5 rgba(0, 88, 174, 255));\n"
"}")
        self.LowerLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LowerLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LowerLeft.setObjectName("LowerLeft")
        self.LowerRight = QtWidgets.QFrame(self.DirFrm)
        self.LowerRight.setGeometry(QtCore.QRect(150, 140, 60, 60))
        self.LowerRight.setStyleSheet("QFrame{\n"
"background-color: qconicalgradient(cx:0.3, cy:0.9, angle:45, stop:0.499 rgba(0, 0, 0, 0), stop:0.5 rgba(0, 88, 174, 255));\n"
"    border: none;\n"
"}")
        self.LowerRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LowerRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LowerRight.setObjectName("LowerRight")
        self.Left = QtWidgets.QFrame(self.DirFrm)
        self.Left.setGeometry(QtCore.QRect(20, 100, 60, 60))
        self.Left.setStyleSheet("QFrame{\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:45, stop:0.749 rgba(0, 88, 174, 0), stop:0.75 rgba(0, 88, 174, 255));\n"
"    border: none;\n"
"}")
        self.Left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Left.setObjectName("Left")
        self.Up = QtWidgets.QFrame(self.DirFrm)
        self.Up.setGeometry(QtCore.QRect(100, 20, 60, 60))
        self.Up.setStyleSheet("QFrame{\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:315, stop:0.749 rgba(0, 0, 0, 0), stop:0.75 rgba(0, 88, 174, 255));\n"
"    border: none;\n"
"}")
        self.Up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Up.setObjectName("Up")
        self.Down = QtWidgets.QFrame(self.DirFrm)
        self.Down.setGeometry(QtCore.QRect(100, 180, 60, 60))
        self.Down.setStyleSheet("QFrame{\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:135, stop:0.749 rgba(0, 0, 0, 0), stop:0.75 rgba(0, 88, 174, 255));\n"
"    border: none;\n"
"}")
        self.Down.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Down.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Down.setObjectName("Down")
        self.CapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CapBtn.setGeometry(QtCore.QRect(40, 400, 121, 81))
        self.CapBtn.setStyleSheet("QPushButton{\n"
"    background-color: #ffbe00;\n"
"    border-radius: 30px;\n"
"}")
        self.CapBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ahmad/.designer/backup/capture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CapBtn.setIcon(icon)
        self.CapBtn.setIconSize(QtCore.QSize(60, 60))
        self.CapBtn.setObjectName("CapBtn")
        self.OnOff = QtWidgets.QFrame(self.centralwidget)
        self.OnOff.setGeometry(QtCore.QRect(240, 400, 80, 80))
        self.OnOff.setStyleSheet("QFrame{\n"
"    background-color: #6b0000;\n"
"    border-radius: 40px;\n"
"    border: 3px solid #ffbe00\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: red;\n"
"}")
        self.OnOff.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OnOff.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OnOff.setObjectName("OnOff")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 500, 121, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(220, 500, 121, 61))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 570, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #ffbe00;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 570, 55, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #ffbe00;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.StchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StchBtn.setGeometry(QtCore.QRect(490, 530, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.StchBtn.setFont(font)
        self.StchBtn.setStyleSheet("QPushButton{\n"
"    background-color: #ffbe00;\n"
"    border-radius: 30px;\n"
"    color: #00365f;\n"
"}")
        self.StchBtn.setIconSize(QtCore.QSize(60, 60))
        self.StchBtn.setObjectName("StchBtn")
        self.CapBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.CapBtn_3.setGeometry(QtCore.QRect(760, 530, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CapBtn_3.setFont(font)
        self.CapBtn_3.setStyleSheet("QPushButton{\n"
"    background-color: #ffbe00;\n"
"    border-radius: 30px;\n"
"    color: #00365f;\n"
"}")
        self.CapBtn_3.setIconSize(QtCore.QSize(60, 60))
        self.CapBtn_3.setObjectName("CapBtn_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot"))
        self.label.setText(_translate("MainWindow", "A"))
        self.label_2.setText(_translate("MainWindow", "V"))
        self.StchBtn.setText(_translate("MainWindow", "Stitching"))
        self.CapBtn_3.setText(_translate("MainWindow", "Stereo Vision"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
