# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stereo_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StereoDialog(object):
    def setupUi(self, StereoDialog):
        StereoDialog.setObjectName("StereoDialog")
        StereoDialog.resize(677, 680)
        StereoDialog.setStyleSheet("QDialog{\n"
"    background-color: #00365f;\n"
"}")
        self.Img = QtWidgets.QLabel(StereoDialog)
        self.Img.setGeometry(QtCore.QRect(40, 40, 601, 491))
        self.Img.setStyleSheet("QLabel{\n"
"    border-radius: 20px;\n"
"    border: 5px solid #ffbe00;\n"
"}")
        self.Img.setText("")
        self.Img.setObjectName("Img")
        self.Img1Btn = QtWidgets.QPushButton(StereoDialog)
        self.Img1Btn.setGeometry(QtCore.QRect(80, 560, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Img1Btn.setFont(font)
        self.Img1Btn.setStyleSheet("QPushButton{\n"
"    background-color: #ffbe00;\n"
"    border-radius: 30px;\n"
"    color: #00365f;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #876b1a;\n"
"}")
        self.Img1Btn.setIconSize(QtCore.QSize(60, 60))
        self.Img1Btn.setObjectName("Img1Btn")
        self.Img2Btn = QtWidgets.QPushButton(StereoDialog)
        self.Img2Btn.setGeometry(QtCore.QRect(420, 560, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Img2Btn.setFont(font)
        self.Img2Btn.setStyleSheet("QPushButton{\n"
"    background-color: #ffbe00;\n"
"    border-radius: 30px;\n"
"    color: #00365f;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #876b1a;\n"
"}")
        self.Img2Btn.setIconSize(QtCore.QSize(60, 60))
        self.Img2Btn.setObjectName("Img2Btn")

        self.retranslateUi(StereoDialog)
        QtCore.QMetaObject.connectSlotsByName(StereoDialog)

    def retranslateUi(self, StereoDialog):
        _translate = QtCore.QCoreApplication.translate
        StereoDialog.setWindowTitle(_translate("StereoDialog", "Stereo Vision"))
        self.Img1Btn.setText(_translate("StereoDialog", "Image 1"))
        self.Img2Btn.setText(_translate("StereoDialog", "Image 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StereoDialog = QtWidgets.QDialog()
    ui = Ui_StereoDialog()
    ui.setupUi(StereoDialog)
    StereoDialog.show()
    sys.exit(app.exec_())
